export enum ActionType {
    GET_LOGGED_IN_USER_INIT = 'GET_LOGGED_IN_USER_INIT',
    GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS',
    GET_LOGGED_IN_USER_ERROR = 'GET_LOGGED_IN_USER_ERROR',
    GET_PLAYERS_INIT = 'GET_PLAYERS_INIT',
    GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS',
    GET_PLAYERS_ERROR = 'GET_PLAYERS_ERROR'
  }